/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 31.12.2025 21:18:36

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1472;
#else
constexpr int kTensorArenaSize = 448;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,99 } };
const TfArray<1, float> quant0_scale = { 1, { 0.037301477044820786, } };
const TfArray<1, int> quant0_zero = { 1, { 11 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[3] = { -4, 0, 8, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00067031255457550287, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[3*10] = { 
  36, 6, 15, -57, -28, 5, 72, -42, -50, 61, 
  11, 51, -40, -43, -44, 11, -5, -38, -3, -15, 
  -33, -24, 127, 22, -36, -22, -40, -27, 44, 8, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.011896234005689621, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -4, 4, 22, 18, -4, -5, -7, 17, 12, -3, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.0005483045824803412, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  5, -27, -25, -5, 48, -1, 30, -42, -4, -27, -4, 8, 11, 32, 8, -31, -9, -11, -30, -6, 
  -31, -38, 39, 17, 13, -15, -20, -33, -33, -7, -24, -18, 65, 8, 8, 37, -14, 68, -20, -11, 
  32, -26, 1, 127, -12, -4, -6, 49, 14, 71, 55, 15, -4, -30, 21, -22, 56, -43, -23, -21, 
  68, 12, 47, 36, -20, 76, -13, 14, 6, 100, 112, 17, -22, -24, 33, -17, 0, -18, 111, 77, 
  -24, 12, -36, -24, -28, 14, -20, -3, -36, 11, 20, 18, -21, 7, -1, -33, -32, 20, 12, 7, 
  -28, 27, -19, 11, -8, -39, -2, 19, -35, -21, 17, 25, -18, 18, -12, -26, -20, 16, -28, -8, 
  24, 24, -19, -25, 47, 21, 6, -17, -5, -9, 14, 17, -27, -10, 6, -7, 16, -4, -11, -20, 
  1, 33, 11, 39, -6, 50, 39, -31, 57, -2, -11, 37, 26, -3, -26, 16, 33, -6, 14, 47, 
  35, 14, 21, 19, 26, 17, -40, -4, -9, 10, 52, 3, 2, -37, -12, 32, -27, 25, -13, -7, 
  11, -23, -2, 1, 50, 32, -6, -2, 37, -33, -18, 20, -27, -15, 27, -7, -12, 22, -3, 18, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0094019044190645218, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 39, -7, 34, 44, -21, 19, -12, 32, 36, 55, 44, 35, 22, -8, -15, -7, 0, -10, 43, 32, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00019074590818490833, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*99] = { 
  -13, 22, -40, 82, 52, 68, 16, -34, 3, -42, 15, 8, -37, -40, 4, 47, 41, 50, -28, -29, 47, -20, 40, -14, -35, 48, -25, -35, -60, -47, 26, 29, -15, -48, -35, -6, 0, 79, -14, -44, -8, -16, -43, -22, -43, 46, -16, 32, -30, -26, -24, -51, 20, -18, -51, 11, 23, 13, 46, 26, -7, -26, -12, -42, -25, -50, -12, 17, 4, 5, 17, 5, -32, 5, -19, -11, 61, 18, -5, 54, 28, -16, 2, 21, -17, -4, -39, -13, -45, -36, 17, -8, -16, 49, -7, -34, 53, 12, -33, 
  -40, -5, 24, 11, -5, 6, 7, 5, 10, 37, -25, 13, 6, 8, 21, -22, 27, 14, 36, -24, -10, -6, 32, -7, 16, 13, -5, 27, -4, -27, -4, 44, 35, 31, 34, -17, -26, 2, 3, -25, -21, -24, 32, 21, 18, -13, 23, -27, 2, 1, -36, -8, -4, -15, -8, -39, -36, 27, 29, -31, -9, 22, -15, -7, -11, -2, 24, -29, 12, -5, 53, -18, 21, -3, 3, 34, -11, -20, -3, 36, -5, -37, -20, -5, 14, -2, -10, -30, 3, -9, 9, 11, 32, 8, -1, 17, -19, -32, 4, 
  17, -12, -43, -23, 29, -18, 16, 25, 29, -5, -34, -1, -32, 13, -23, 22, 8, 17, 1, 11, 33, -37, 22, -30, 3, -10, 36, 18, -20, -34, -22, 26, 22, -36, 1, -22, -28, 4, 14, -38, 12, 11, -43, -14, 9, -10, -23, -33, 10, -10, 14, -12, -12, -5, 15, -35, -2, -1, -1, -17, 28, -17, -10, 1, -15, 19, -1, -14, -23, -8, 3, -37, -4, 28, -12, -32, -34, 17, -24, -25, 13, -26, 9, -9, -4, 1, -15, -7, -36, -5, -31, 28, 5, -17, 31, 22, 6, 12, 8, 
  -42, 2, -45, 61, 15, 28, -10, 25, 8, -36, 23, 21, 9, 16, 14, -14, -30, -26, 13, 18, -29, 9, -33, -17, 24, 14, -35, 29, 32, 17, -21, 19, 26, -30, 38, -14, 70, -32, -5, 13, -45, 11, -12, 21, 35, -30, -7, -33, 13, 16, -37, -7, -11, -46, 0, -41, -41, -48, -19, -15, 23, 5, 29, 17, -33, -43, 9, -25, -47, -28, 54, -18, -33, -33, -1, 14, -14, 31, 4, 26, 2, 13, 17, -18, -18, -41, -9, -25, 14, -22, 10, 7, -36, 6, 24, -21, -27, -17, 25, 
  61, 28, 22, -21, -27, -27, 57, 5, -14, 15, -14, 15, -21, -24, -19, 33, 34, 55, -2, 3, 8, 50, -6, -4, -1, 7, 22, 23, -34, -35, 3, -16, 10, -20, -9, -11, -19, -35, 31, 60, 25, 32, -26, -5, 47, -15, 51, 41, -9, 42, 56, 31, -21, -7, -2, 65, 53, 54, 41, 50, -28, -23, 42, 40, 10, 19, -9, 6, -29, -19, -39, 28, 43, 34, 25, 22, -5, -4, -11, -8, 52, -31, 54, -17, 33, -13, 23, -20, 45, -5, -6, 8, 32, 46, 42, 13, 24, 12, -10, 
  -8, 21, -8, 6, -5, -10, -1, 49, -26, 48, -31, -15, -34, 43, 55, -3, -29, 17, 1, 24, -26, -24, 17, 2, 74, 0, 24, 24, 0, 82, 4, 31, 43, -20, 15, -41, 46, -15, 15, 29, 47, 9, -22, -8, 32, -29, -23, -19, 8, 73, 64, 0, 27, -9, 49, 33, 29, -5, 35, 11, 16, -32, 52, -24, -6, 6, -11, 29, 19, 27, 57, -2, 21, -23, -36, -14, 4, -6, 39, 14, -22, 11, -13, 45, 2, -24, 24, 3, 47, 1, 11, 12, -18, 52, 7, 5, -6, 20, 11, 
  38, -1, -9, -23, -25, -33, -8, 54, -8, 8, 6, 3, 6, 38, 22, 0, -11, -15, 58, 53, -13, 13, -13, 28, -10, 2, 56, -28, 29, 17, 32, -32, 4, 1, -28, 45, -39, 9, -26, 73, 1, 21, 3, 10, -15, -28, 66, -17, 1, -4, -21, 56, -28, 42, 25, 2, 11, 59, 37, -9, -20, 12, 47, -19, 34, 19, -30, 15, -24, -27, -1, 58, -6, 38, 25, 39, 37, 57, 33, -12, 47, 47, 9, 29, -17, -5, 47, 22, -13, -12, -23, 45, -10, 64, -7, -33, -13, -18, -29, 
  33, -46, -3, 21, 22, 15, 27, 6, -6, 39, -2, 57, -19, 24, -40, -29, 2, -23, -14, 52, 44, -21, -23, -3, -5, 45, -12, 17, -45, -10, 21, 42, 20, -35, -19, -40, -11, 5, 37, -17, -9, 17, 25, 47, 8, 2, 16, -36, -25, 10, -30, 3, -15, 17, -25, -24, -36, 42, 44, -40, -27, -7, 30, -30, 49, 43, 3, 0, -32, 31, -31, -4, -4, 14, 6, 12, -28, 19, -34, 0, 29, -38, 14, -13, 6, -44, 25, 17, 30, -25, -16, -34, 3, -15, -38, -27, -7, -47, -19, 
  24, 9, 11, 10, -21, 82, -4, -30, -9, 6, -2, 23, 20, -3, 33, -16, 23, -11, 92, 34, 60, 67, 76, 68, 50, 32, 41, 24, 78, -25, 72, -26, 13, -3, -21, -22, -25, 53, -29, -3, -17, -24, -30, -15, -27, 27, -8, 6, -12, 44, -28, -30, 56, -15, 47, 24, 8, 33, 5, -9, 30, -2, 60, -7, 14, -29, 33, 59, 12, -2, 10, 20, 8, -26, -11, -25, -26, -11, -15, 53, -20, -22, -28, -12, 58, 9, 1, 21, 24, 31, 7, -28, -28, 6, 38, 7, 72, 31, 10, 
  -43, -15, -66, 25, -4, 127, -44, -21, -38, -30, -32, -43, -48, -8, -4, 35, -2, 14, 71, -22, -7, 27, 32, 88, 90, 52, 20, 33, 22, 40, 4, 13, -27, -21, 71, -15, 104, 109, -25, -21, -8, -2, -37, -5, -17, -29, 28, 15, 51, -22, 22, 45, -42, -37, -22, 4, 19, 1, -37, 3, -40, -28, -25, 28, -7, -4, -53, -5, -59, 62, -5, 55, 17, -6, -16, -24, 38, -18, -46, 26, 38, 25, -45, -31, -39, 18, -35, -30, 10, 3, 27, 11, -8, -6, -7, 36, -12, -54, -39, 
  26, -7, -12, -32, -27, 0, 13, -7, -19, 49, -37, 1, -3, -35, 50, -30, 3, -14, 19, 18, -47, 17, -30, 54, 60, -6, -28, -10, 71, 44, -32, -2, -53, -23, 75, 12, 10, -19, -47, -11, 2, -23, -13, -21, -11, 39, 4, -38, 21, 35, -14, -33, -15, -5, 27, 25, -28, -29, 4, -8, 2, 8, 21, 20, 8, -34, -45, 22, -11, 45, 76, 22, -22, -19, -12, 74, 8, -27, 22, 43, -18, -32, 10, -35, -22, 20, -21, 14, -23, -20, 0, 35, 15, -21, -8, 1, -26, 13, -38, 
  1, -17, 33, -20, -33, -26, 59, -10, 37, 0, 37, 48, 29, 57, -6, 36, -6, -5, 77, 14, 1, 4, 69, 16, 26, 38, 35, 39, 64, 21, -1, 10, -4, -9, 34, -8, -26, 6, 24, 43, 48, 50, 59, 1, -11, 0, 32, 45, -26, 21, -20, 60, 35, 33, 68, 38, 46, 2, 19, -23, 58, 46, 10, -3, 52, 52, 39, -16, -6, -15, -33, 3, -18, -17, 46, 23, 17, 48, 18, 16, 34, 48, -24, -14, -30, -28, -20, 21, -4, 44, 32, -26, -31, -23, 16, 27, 44, 47, 0, 
  -25, -37, 11, -14, 28, -61, -30, -41, -34, -3, -26, -43, -2, 9, -34, 11, -16, -24, 12, -29, 5, 6, -41, 7, -4, -24, -13, -34, 13, -23, -34, -16, -25, 28, 5, 19, 24, -31, -33, -20, -11, 0, -30, -25, -53, -32, 24, 11, -16, 20, 15, -44, -47, -4, -34, -42, -38, 3, -19, -1, -22, -42, -41, 10, -9, -2, 18, 25, 7, 27, -1, -37, 17, 11, 1, -58, -29, 17, -39, -38, -18, 4, 19, 14, 33, 22, -44, -28, -5, 9, -35, 22, -6, -8, -34, -42, 0, -7, 10, 
  18, -29, -14, -18, 19, 22, -28, 69, 3, 3, 14, 24, 57, 10, -18, -22, -39, -1, -35, -11, -24, -28, -8, -18, -14, -35, -19, 22, -10, -4, 9, -34, -21, -33, -7, 33, 5, -14, 63, -6, 60, 45, 65, -24, 39, -20, 3, 32, 50, 22, 23, 27, -24, -15, 38, -10, 11, 47, 33, -3, 5, -10, -4, -27, 37, 29, 59, 26, 28, 23, -45, -10, 53, -1, 37, -28, -16, -12, 29, -17, -11, 33, -6, -8, 38, 16, 49, 49, 3, -33, 9, 13, -21, 27, -32, -24, -11, 61, 8, 
  64, -25, -17, -2, -6, -17, -13, 30, 37, 22, 58, -34, -29, 51, -33, -10, -30, 13, 36, -25, 57, 59, -15, 41, -30, -17, 0, -27, 33, -5, 42, -16, -11, 48, 2, -21, -35, 2, 59, -32, -34, 58, -33, 48, -1, 45, -9, -20, -33, -12, -1, 33, 27, -1, -24, -20, 65, -4, 61, -17, 9, 32, -18, 58, 15, 60, 63, 12, -2, 12, -3, -19, 61, -11, 57, 30, -12, 21, 5, 9, 39, 10, -21, -13, 19, -26, 55, 12, -27, 17, -13, 23, 0, 39, -28, 7, 57, 60, 59, 
  -7, 38, -33, -32, -32, 5, -13, -2, 7, 8, -8, 8, -25, 12, 13, 22, -1, 9, 6, 15, -42, 25, -35, 11, 2, -8, -21, -16, -9, -24, 5, -16, -14, 12, 3, 2, 5, -32, 2, 26, 14, -26, 4, -35, 21, -29, -42, -17, -33, 19, 8, -10, 19, 25, 9, -28, 26, 9, -34, 25, -6, -29, 0, -22, -1, 10, -2, -16, -4, 42, -30, 29, 24, 26, 10, 23, -20, 3, 26, 8, -30, -29, -3, 28, 32, 22, -4, 13, 16, 32, -8, 33, 1, 18, 29, 20, -39, 12, 14, 
  2, -21, -20, -5, 27, -2, -8, -20, 29, -22, -27, -11, -2, 16, -15, 12, -21, -24, 38, 1, -33, -18, -1, 2, 25, -14, -11, 27, -18, 50, 11, 9, 8, -22, 3, -19, 7, -35, -13, 9, 0, -7, 9, 43, -5, -24, 31, -38, -12, -13, 5, 0, -8, -35, -7, -49, -6, -11, 21, -28, -30, 65, -25, -3, -25, 38, 1, -34, 5, 27, -39, -17, -33, 38, 37, 21, -25, 10, -37, -19, 20, 36, -44, -13, -10, 20, -3, -26, 47, -11, 3, 44, 36, 5, -4, -22, 3, -17, 47, 
  -18, 9, 52, 18, 20, -27, -29, 21, 1, -28, -26, 23, -25, 17, -42, -19, -46, -1, 8, -34, 11, -24, -36, 21, -26, -41, -23, -6, -14, -31, -12, -44, -7, 3, 4, 38, 49, -19, 21, -33, -37, -16, 31, -23, -5, -43, -12, 24, -34, 1, -22, -38, 23, 9, -1, -32, 17, -36, -22, -26, 7, -43, 10, 24, -20, 3, -13, 3, 16, -18, 24, -35, 17, 18, 4, -17, -42, -40, 13, -31, -49, -40, -37, -7, 9, 25, -27, -3, -3, 1, -13, 24, -47, -37, 18, 3, 7, -20, 17, 
  -33, -22, 2, -28, 51, 81, -32, -16, -10, 23, -28, -20, -32, -20, 4, -21, 6, -24, -16, 30, -23, 61, -11, 98, -12, -33, 30, 3, -3, -13, 76, 8, -12, -43, 73, 14, 39, -16, -40, -30, -36, -7, -33, 15, 7, 3, 45, 16, -24, -23, 7, -31, 18, -17, 53, -29, -21, -26, -4, 28, -18, -21, -19, 61, 16, -19, 22, -25, -21, 107, 94, 54, 14, -26, -41, 61, 52, 1, -7, 10, 34, 10, 34, -8, 7, -5, 34, 5, -13, -37, -40, 39, 23, -12, -38, -34, 17, 1, 43, 
  3, 21, -13, -12, -1, 32, 9, -8, 26, 76, -25, 35, 31, 9, 39, -9, 7, -27, -12, 34, -13, -28, 77, -16, 19, 7, -14, -2, 60, 73, -14, 54, 86, -22, 17, 1, -29, 21, -1, -13, -22, -29, 10, 23, 10, -23, -30, 28, 7, 30, 29, 37, -28, 29, 47, -14, 46, -26, -19, 54, -25, 52, -22, 30, -23, 4, -5, -23, -41, -16, -31, 77, -9, -2, -6, 55, -26, -33, -28, -9, 72, 0, 5, -29, -3, 18, 60, 1, 13, 5, -31, 12, -20, -1, 13, -27, -20, -24, 42, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,99 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0051136286929249763, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.05831846222281456, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.056346617639064789, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfArray<1, float> quant9_scale = { 1, { 0.10499179363250732, } };
const TfArray<1, int> quant9_zero = { 1, { -16 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 99, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1980, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 112), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_861146_6_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_861146_6_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_861146_6_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_861146_6_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_861146_6_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
